config/routes.rb
Rails.application.routes.draw do

  namespace :timetablings do
    get 'step_one/index'
    post 'step_two/index'
  end
  #### timetablings_controller

  post 'timetablings/create'

  get 'timetablings/show'

  get 'timetablings/index'

  #### home_controller
  get 'home/index'

  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	validates :name, uniqueness: true, presence: true
	has_many :restrictions
end

app/models/discipline.rb
class Discipline < ApplicationRecord
  belongs_to :course
  has_many :prerequisites

  validates :name, uniqueness: { scope: [:course_id, :name] }, presence: true


  scope :by_course_ids, -> (ids) { where(course_id: ids) }
end

app/models/log_timetabling.rb
class LogTimetabling < ApplicationRecord
end

app/models/prerequisite.rb
class Prerequisite < ApplicationRecord
  belongs_to :discipline
  validates :discipline_id, uniqueness: { scope: [:pre_req, :discipline_id] }
end

app/models/restriction.rb
class Restriction < ApplicationRecord
  belongs_to :course

  validates :week_day, :start_time, :end_time, :course_id, :restriction_type, presence: true
  validates :course_id, uniqueness: { scope: [:week_day, :start_time, :end_time, :situation] }

  enum restriction_type: [:hard, :soft]

  scope :hard, -> (course_id) { where(restriction_type: 0, course_id: course_id, situation: true) }
  scope :soft, -> (course_id) { where(restriction_type: 1, course_id: course_id, situation: true) }

end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :timeslots

  scope :actives, -> { where(situation: true) }
end

app/models/time_record.rb
class TimeRecord < ApplicationRecord
end

app/models/timeslot.rb
class Timeslot < ApplicationRecord
  belongs_to :teacher
  belongs_to :discipline
  belongs_to :timetabling
end

app/models/timetabling.rb
class Timetabling < ApplicationRecord
  belongs_to :course
  has_many :timeslots

  scope :collection_by_ids_ascending, -> (ids) { where(id: ids).order(period: :asc) }
  scope :order_by_period, -> { all.order(period: :asc).order(situation: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/timetablings/step_one_controller.rb
class Timetablings::StepOneController < ApplicationController
  def index
    @cursos = Course.all
  end
end

app/controllers/timetablings/step_two_controller.rb
class Timetablings::StepTwoController < ApplicationController
  def index
    @curso = Course.find(course_id_params)
    @disciplinas = Discipline.by_course_ids(course_id_params)
    @period = period_params
    @professores = Teacher.actives
  end

  private

  def period_params
    params[:period]
  end

  def course_id_params
    params[:course_id]
  end
end

app/controllers/timetablings_controller.rb
class TimetablingsController < ApplicationController
  def index
    @log_timetabling = LogTimetabling.all.order(id: :desc)
    @time_record = TimeRecord.last
  end

  def show
    @timetablings = Timetabling.collection_by_ids_ascending(timetabling_ids_params)
  end

  def create
    TimetablingService.create(params)

    redirect_to timetablings_index_path
  end

  private

  def timetabling_ids_params
    params[:ids_timetabling]
  end

end

app/controllers/timetablings_controller/timetabling_service.rb
class TimetablingsController::TimetablingService
  def self.create(params)

    course_id = Discipline.find(JSON[params["time_slot_1"]][0]).course_id

    n_periods = Course.find(course_id).n_periods

    iteracoes = params[:iteracoes]

    first_param = JSON[params["time_slot_1"]]

    #colecao de restricoes hard
    hr = []
    Restriction.hard(course_id).each do |r|
      hr << { week_day: r.week_day, start_time: r.start_time, end_time: r.end_time }
    end

    #colecao de restricoes soft
    sr = []
    Restriction.soft(course_id).each do |r|
      sr << { week_day: r.week_day, start_time: r.start_time, end_time: r.end_time, weight: r.weight }
    end

    # variavel para armazenar as hashes de timeslot
    timeslots = []

    #variavel para contar os timeslots equivalenta a utilizada na view step_2
    time_slot_count = 1

    # loop para armazenar os dados recebidos
    loop do
      if params.has_key?("time_slot_#{time_slot_count}")

        ts = JSON[params["time_slot_#{time_slot_count}"]]
        discipline = Discipline.find(ts[0])
        timeslots << { :discipline_id => ts[0],
                       :teacher_id => ts[1],
                       :period => discipline.period,
                       :credits => discipline.credits }

        time_slot_count += 1
      else
        break
      end
    end

    #registra tempo de inicio
    time_record = TimeRecord.create(start_time: Time.now)

    HeuristicMonography.execucao_iterada(iteracoes, timeslots, course_id, n_periods, hr, sr)

    #registra tempo de finalizacao
    time_record.update(end_time: Time.now)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def is_active_controller(controller_name, class_name = nil)
        if params[:controller] == controller_name
         class_name == nil ? "active" : class_name
        else
           nil
        end
    end

    def is_active_action(action_name)
        params[:action] == action_name ? "active" : nil
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/timetablings/step_1_helper.rb
module Timetablings::Step1Helper
end

app/helpers/timetablings/step_2_helper.rb
module Timetablings::Step2Helper
end

app/helpers/timetablings_helper.rb
module TimetablingsHelper

  def retorna_hash_timetabling(t_id)

    tm = []
    period = Timetabling.find(t_id).period
    timeslots = Timetabling.find(t_id).timeslots

    timeslots.each do |t|
      tm << { week_day: t.week_day,
              start_time: t.start_time,
              end_time: t.end_time,
              teacher_id: t.teacher_id,
              discipline_id: t.discipline_id,
              period: period,
              credits: Discipline.find(t.discipline_id).credits }
    end
    return tm
  end

  #helper utilizado na view
  def retorna_hr(t_id)
  #colecao de restricoes hard
  course_id = Timetabling.find(t_id).course_id
  hr = []
  Restriction.where(restriction_type: 0, course_id: course_id, situation: true).each do |r|
    hr << { week_day: r.week_day,
        start_time: r.start_time,
        end_time: r.end_time }
  end
    return hr
  end

  #helper utilizado na view
  def retorna_sr(t_id)
  #colecao de restricoes soft
  course_id = Timetabling.find(t_id).course_id
  sr = []
  Restriction.where(restriction_type: 1, course_id: course_id, situation: true).each do |r|
    sr << { week_day: r.week_day,
        start_time: r.start_time,
        end_time: r.end_time,
        weight: r.weight }
  end
  return sr
  end

  #helper utilizado na view
  def retorna_disciplinas(period, course_id)
    Discipline.where(course_id: course_id, period: period).order(:name)
  end

  def calc_period(period)
    period == "Ímpar" ? 1 : 2
  end

  def checa_timetabling(timetabling, hr, sr)
    HeuristicMonography.checa_timetabling(timetabling, hr, sr)
  end
end

app/views/home/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Home</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to "Dashboards", root_path %>
            </li>
            <li class="active">
                <strong>Home</strong>
            </li>
        </ol>
    </div>
</div>

app/views/timetablings/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Log de Tabelas</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to "Home", root_path %>
            </li>
            <li class="active">
                <strong>Tabelas Ativas</strong>
            </li>
        </ol>
    </div>
</div>

<% if @time_record.present? %>
    <div class="wrapper wrapper-content">
        <div class="row animated fadeInDown">
            <div class="col-sm-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>Registro de Tempo</h5>
                        </div>
                        <div class="ibox-content">
                            <p>Início: <%= @time_record.start_time %></p>
                            <p>Fim: <%= @time_record.end_time %></p>
                        </div>
                    </div>
                <% @log_timetabling.each do |l| %>
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <div class="row">
                                <div class="col-sm-6">
                                    <h5>
                                        Tabelas: <%= JSON[l.log_timetabling] %>, Peso: <%= l.peso %>, Iteração Nº <%= l.n_iteration %>
                                    </h5>

                                </div>
                                <div class="col-sm-2 pull-right">
                                    <%= link_to "Mostrar",
                                            timetablings_show_path(ids_timetabling: JSON[l.log_timetabling]),
                                            class: 'btn btn-primary' %>
                                </div>
                            </div>
                        </div>
                        <div class="ibox-content">
                            <% (JSON[l.log_timetabling]).each do |id| %>
                                <% timetabling = Timetabling.find(id) %>
                                <p>
                                    Periodo: <%= timetabling.period %>, Peso: <%= checa_timetabling(retorna_hash_timetabling(timetabling.id), retorna_hr(timetabling.id), retorna_sr(timetabling.id)) %>
                                </p>
                            <% end %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
<% end %>

app/views/timetablings/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Nova Tabela</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to "Home", root_path %>
            </li>
            <li class="active">
                <strong>Tabelas Ativas</strong>
            </li>
        </ol>
    </div>
</div>

<div class="wrapper wrapper-content">
    <div class="row animated fadeInDown">

        <% @timetablings.each do |t| %>
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5><%= t.period %>º Período, Peso: <%= checa_timetabling(retorna_hash_timetabling(t.id), retorna_hr(t.id), retorna_sr(t.id)) %>
                        </h5>
                    </div>
                    <div class="ibox-content">
                        <div id="calendar_<%= t.id %>"></div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>


<% content_for :javascript do %>

<script type="text/javascript">


$(function() {

    $('.i-checks').iCheck({
        checkboxClass: 'icheckbox_square-green',
        radioClass: 'iradio_square-green',
    });

    /* initialize the external events
     -----------------------------------------------------------------*/


    $('#external-events div.external-event').each(function () {

        // store data so the calendar knows to render an event upon drop
        $(this).data('event', {
            title: $.trim($(this).text()), // use the element's text as the event title
            stick: true // maintain when user navigates (see docs on the renderEvent method)
        });

        // make the event draggable using jQuery UI
        $(this).draggable({
            zIndex: 1111999,
            revert: true,      // will cause the event to go back to its
            revertDuration: 0  //  original position after the drag
        });

    });


    /* initialize the calendar
     -----------------------------------------------------------------*/

    <% @timetablings.each do |t| %>

        $('#calendar_<%= t.id %>').fullCalendar({
            header: {
                left: 'today',
                // left: 'prev,next today',
                // center: 'title',
                right: 'agendaWeek'
                // right: 'month,agendaWeek,agendaDay'
            },
            lang: 'pt-br',
            editable: false,
            droppable: false, // this allows things to be dropped onto the calendar
            drop: function () {
                // is the "remove after drop" checkbox checked?
                if ($('#drop-remove').is(':checked')) {
                    // if so, remove the element from the "Draggable Events" list
                    $(this).remove();
                }
            },
            defaultView: 'agendaWeek',
            events: [
                <% t.timeslots.each do |ts| %>
                    {   
                        <% day = ts.week_day.to_date %>
                        title: '<%= ts.discipline.name %>',
                        start: new Date(<%= day.strftime("%Y").to_i %>,
                                        <%= day.strftime("%m").to_i %> - 1,
                                        <%= day.strftime("%d").to_i %>,
                                        <%= ts.start_time.to_time.strftime("%H").to_i %>,
                                        <%= ts.start_time.to_time.strftime("%M").to_i %>),
                        end: new Date(<%= day.strftime("%Y").to_i %>,
                                      <%= day.strftime("%m").to_i %> - 1,
                                      <%= day.strftime("%d").to_i %>,
                                      <%= ts.end_time.to_time.strftime("%H").to_i %>,
                                      <%= ts.end_time.to_time.strftime("%M").to_i %>),
                        description: 'Prof: <%= ts.teacher.name %>'
                    },
                <% end %>
            ],
            eventColor: '#1197c1',
            eventRender: function(event, element) { 
                element.find('.fc-title').append("<br/>" + event.description); 
            },
        });
    <% end %>

    /* initialize the calendar
     -----------------------------------------------------------------*/
    // var date = new Date();
    // var d = date.getDate();
    // var m = date.getMonth();
    // var y = date.getFullYear();

    // $('#calendar').fullCalendar({
    //     header: {
    //         left: 'prev,next today',
    //         center: 'title',
    //         right: 'month,agendaWeek,agendaDay'
    //     },
    //     editable: true,
    //     droppable: true, // this allows things to be dropped onto the calendar
    //     drop: function () {
    //         // is the "remove after drop" checkbox checked?
    //         if ($('#drop-remove').is(':checked')) {
    //             // if so, remove the element from the "Draggable Events" list
    //             $(this).remove();
    //         }
    //     },
    //     events: [
    //         {
    //             title: 'All Day Event',
    //             start: new Date(y, m, 1)
    //         },
    //         {
    //             title: 'Long Event',
    //             start: new Date(y, m, d - 5),
    //             end: new Date(y, m, d - 2),
    //         },
    //         {
    //             id: 999,
    //             title: 'Repeating Event',
    //             start: new Date(y, m, d - 3, 16, 0),
    //             allDay: false,
    //         },
    //         {
    //             id: 999,
    //             title: 'Repeating Event',
    //             start: new Date(y, m, d + 4, 16, 0),
    //             allDay: false
    //         },
    //         {
    //             title: 'Meeting',
    //             start: new Date(y, m, d, 10, 30),
    //             allDay: false
    //         },
    //         {
    //             title: 'Lunch',
    //             start: new Date(y, m, d, 12, 0),
    //             end: new Date(y, m, d, 14, 0),
    //             allDay: false
    //         },
    //         {
    //             title: 'Birthday Party',
    //             start: new Date(y, m, d + 1, 19, 0),
    //             end: new Date(y, m, d + 1, 22, 30),
    //             allDay: false
    //         },
    //         {
    //             title: 'Click for Google',
    //             start: new Date(y, m, 28),
    //             end: new Date(y, m, 29),
    //             url: 'http://google.com/'
    //         }
    //     ],
    // });


});

</script>

<% end %>

app/views/timetablings/step_one/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Nova Tabela</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to "Home", root_path %>
            </li>
            <li class="active">
                <strong>Nova Tabela</strong>
            </li>
        </ol>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-sm-12">

            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Nova Tabela de Horários</h5>
                </div>
                <div class="ibox-content">
                    <p>Escolha o Curso e em qual período deseja gerar tabelas.</p>
                    <%= form_with(url: timetablings_step_two_index_path, local: true, class: "form-horizontal m-t-md") do |f| %>
                        <div class="row">
                            <div class="form-group">
                                <div class="col-sm-6">
                                    <div class="col-sm-2">
                                        <label class="font-normal control-label">Cursos</label>
                                    </div>
                                    <div class="col-sm-10">
                                        <div>
                                            <% cursos_array = @cursos.map { |c| [ c.name, c.id ] } %>

                                            <%= f.select(:course_id ,options_for_select(cursos_array), {:prompt => ' --- Selecione o Curso --- '}, {class: 'chosen-select', tabindex: '2'}) %>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-sm-6" style="padding-left: 30px;">
                                    <div class="form-group">
                                        <div class="col-sm-6">
                                            <div class="radio">
                                                <%= f.radio_button(:period, "Par", required: 'required', id: 'r1') %>
                                                <%= f.label(:period, "Período Par", for: 'r1') %>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="radio">
                                                <%= f.radio_button(:period, "Ímpar", id: 'r2') %>
                                                <%= f.label(:period, "Período Ímpar", for: 'r2') %>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <p>
                            <%= f.submit("Continuar", class: 'btn btn-w-m btn-primary') %>
                        </p>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

<% content_for :javascript do %>
<script type="text/javascript">

    $(function() {
        $('.chosen-select').chosen({width: "100%"});
    });

</script>
<% end %>

app/views/timetablings/step_two/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Seleção de Professores</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to "Home", root_path %>
            </li>
            <li>
                <%= link_to "Nova Tabela", timetablings_step_one_index_path %>
            </li>
            <li class="active">
                <strong>Seleção de Professores</strong>
            </li>
        </ol>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-sm-12">

            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Nova Tabela de Horários</h5>
                </div>
                <div class="ibox-content">
                    <p>
                        Escolha os professores que lecionarão as disciplinas.
                    </p>
                </div>
            </div>
        </div>
    </div>

    <%= form_with(url: timetablings_create_path, local: true, class: "form-horizontal") do |f| %>
        <div class="row">
        <% time_slot_count = 1 %>
            <% aux = calc_period(@period) %>
            <% loop do %>
                <div class="col-sm-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <%# aux é o numero correspondente ao periodo %>
                            <h5><%= aux %>º Período</h5>
                        </div>
                        <div class="ibox-content">

                            <% disciplinas = retorna_disciplinas(aux, @curso.id) %>

                            <% disciplinas.each do |d| %>
                                <div class="form-group">

                                    <label class="col-sm-4 control-label"><%= d.name %></label>

                                    <div class="col-sm-8">
                                        <div>
                                            <% prof_array = @professores.map { |p| [ p.name, "#{[d.id, p.id]}" ] } %>

                                            <%= f.select("time_slot_#{time_slot_count}" ,options_for_select(prof_array), {:prompt => ' --- Selecione o Professor --- '}, {class: 'chosen-select', tabindex: '2'}) %>
                                            <% time_slot_count += 1 %>
                                        </div>
                                    </div>
                                </div>

                                <div class="hr-line-dashed"></div>
                            <% end %>

                        </div>
                    </div>
                </div>

                <% aux = aux + 2 %>
                <% break if aux > @curso.n_periods %>
            <% end %>

            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-content">
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Número de Iterações:</label>
                            <div class="col-sm-3">
                                <%= f.number_field :iteracoes, in: 1..10000, required: true, class: 'form-control', style: 'margin: 5px;' %>
                            </div>
                            <div class="col-sm-2">
                                <%= f.submit("Criar Tabelas", class: 'btn btn-w-m btn-primary', style: 'margin: 5px;') %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    <% end %>
</div>

<% content_for :javascript do %>

<script type="text/javascript">

    $(function() {

        $('.chosen-select').chosen({width: "100%"});

    });

</script>

<% end %>